### ISSUE TITLE
优先级

### ISSUE THREAD

**Issue by nicoGateKeeper** [cocos2d/cocos2d-x-docs#101]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/event_dispatcher/priority.md

**Comment by nicoGateKeeper** [comment]
mark

**Comment by drelaptop** [comment]
你好，这一节文档的叙述存在什么问题吗？ @nicoGateKeeper

**Comment by nicoGateKeeper** [comment]
没有，只是手残点错了，不好意思

**Comment by drelaptop** [comment]
欢迎阅读文档，学习 Cocos2d-x
