### ISSUE TITLE
Pre-built Libraries

### ISSUE THREAD

**Issue by KAMIKAZEUA** [cocos2d/cocos2d-x-docs#106]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/editors_and_tools/prebuilt_libraries.md

I can’t find any useful information of how to work with prebuilt libraries. Not step by step guide. 
How can I setup a new project for android with prebuilt libs? 
Also, for iOS it's simple, but anyway there should be a guide for any platform. 
  
Moreover, prebuilt libraries should be n1 "feature" while using cocos2d-x. 
It saves time considerably and easy to use one cocos2d-x lib for many games. 
Also, if source code needed - it's so simple easy to add it into Xcode just by drag and drop cocos2d-x project file(with proper settings before). Well, for me actually, during 1.5 year of development of 1 game - I never needed source code, like for debugging.

**Comment by drelaptop** [comment]
Thanks for mention it. @slackmoehrle shell we write `Pre-built Libraries` docs first? I saw many developers have doubt about it, wonder this on English Forum, Chinese Forum, even Cocos2d-x's PR comments.

**Comment by KAMIKAZEUA** [comment]
I would suggest you even push prebuilts like official manner of how to use this engine. 
It's would be so easy and fast to use. Created project. Build & run instantly. No need to wait 5-10min to compile a heavy bunch of source code.

**Comment by drelaptop** [comment]
What's your opinion @minggo on this suggestion? minggo is the main member of cocos2d-x team.

**Comment by KAMIKAZEUA** [comment]
Yea, I know, but before that I've already suggested something like that and\or asking about prebuilts, like how to use them and so on. But got no response overall.

**Comment by drelaptop** [comment]
minggo is busy recently, I will do prebuilts docs in this week.

**Comment by slackmoehrle** [comment]
Ios is documented but can use updating and work. Android we should just document Android Studio.

**Comment by minggo** [comment]
@drelaptop i think you can do it after using Cmake for all platforms, it may be easier.

**Comment by drelaptop** [comment]
OK, I will. using Cmake is a better way to build `Pre-built Libraries`

**Comment by drelaptop** [comment]
CMake have supported prebuilt libs, Refer to https://github.com/cocos2d/cocos2d-x/blob/v3/cmake/README.md
