### ISSUE TITLE
Script component documentation issue

### ISSUE THREAD

**Issue by tomcam** [cocos2d/cocos2d-x-docs#107]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/scripting/script_component.md

Just learning Cocs2d-JS so this may be covered elsewhere, but this doesn't tell me where to get the Cocos engine files (maybe CCBoot.js? jsb.js?  not sure) and how to include them in my Javascript file (import statement? script tag?)

**Comment by drelaptop** [comment]
https://github.com/cocos2d/cocos2d-x/tree/v3/tests/js-tests

the `js-tests` project will do some help for you, and we suggest the developers prepare to use `cocos2d-js` change to use `Cocos Creator`, [Creator Docs](http://www.cocos2d-x.org/docs/creator/en/)

**Comment by tomcam** [comment]
Just what I needed.Thanks.
