### ISSUE TITLE
按钮(Button)

### ISSUE THREAD

**Issue by jacoby24** [cocos2d/cocos2d-x-docs#115]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/ui_components/buttons.md

how could I call a api with lua? It is all the c++ function.

**Comment by drelaptop** [comment]
You can find the api in [api docs](http://www.cocos2d-x.org/docs/api-ref/cplusplus/v3x/), click the switch button on the top right to change the content into Lua. Such as [Lua API - Button](http://www.cocos2d-x.org/docs/api-ref/cplusplus/v3x/d2/db1/classcocos2d_1_1ui_1_1_button.html#adf271b1be4c753b7f9ddf23e8f67c530)


As for [docs/cocos2d-x](http://cocos2d-x.org/docs/cocos2d-x/en/) not exist example writing with Lua code, we prefer Lua developers to add that, you know cocos2d-x is an open source engine, and this docs also is an open source document, add Lua code is easy, you can refer to the instrument [how-to-contribute-to-our-projects](http://docs.cocos.com/cocos2d-x/manual/en/about/how.html#how-to-contribute-to-our-projects).
