### ISSUE TITLE
UI 组件

### ISSUE THREAD

**Issue by jacoby24** [cocos2d/cocos2d-x-docs#118]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/ui_components/index.md

It is too difficult to find the function of one such as button,sprite and so on. This api docs is useless. Though lua is easy, but I can't find the right way to use it in cocos. I'm sad.

**Comment by drelaptop** [comment]
api docs is here : http://www.cocos2d-x.org/docs/api-ref/cplusplus/v3x/ , you can skip into the api docs by api-ref button on the  top-bar

docs here http://docs.cocos.com/cocos2d-x/manual/en/ is published to help the new developers to get some knowledges about Cocos2d-x
