### ISSUE TITLE
Creator to Cocos2d-x 插件

### ISSUE THREAD

**Issue by lyzz0612** [cocos2d/cocos2d-x-docs#126]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/editors_and_tools/creator_to_cocos2dx.md

>    local creatorReader = cc.CreatorReader:createWithFilename('creator/CreatorSprites.ccreator')
> [:memo:](https://github.com/cocos2d/cocos2d-x-docs/edit/master/zh/editors_and_tools/creator_to_cocos2dx.md#L167 "Edit") <https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/editors_and_tools/creator_to_cocos2dx.md#L167>

the CreatorReader seems to be in `creator` module rather than `cc`

**Comment by drelaptop** [comment]
You said the truth, thanks for feedback this

Here is example code we can refer to.
https://github.com/minggo/cocos2d-x/blob/3ef7bd051f24de23767898b668c56cc34e7dee31/tests/lua-empty-test/src/mainscene.lua#L16
