### ISSUE TITLE
最后一句“如何发发生”应为“如何发生”吧

### ISSUE THREAD

**Issue by SingleShadow** [cocos2d/cocos2d-x-docs#133]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/basic_concepts/director.md

**Comment by drelaptop** [comment]
thanks, GitHub 的已经更改了，中文网站，文档同步有较大延迟

**Comment by slackmoehrle** [comment]
同步发生在每晚。是失败的？我的更改正在部署。
