### ISSUE TITLE
Win10，vs2015环境，cpp-texts编译成功，运行出错。

### ISSUE THREAD

**Issue by chenyuxiangg** [cocos2d/cocos2d-x-docs#137]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/installation/Windows.md

错误提示为访问冲突

**Comment by drelaptop** [comment]
什么访问冲突，贴一下报错的详细信息，截图之类

**Comment by chenyuxiangg** [comment]
手机上贴不了图我写一下吧：

0x00000000处（位于cpp-texts.exe）引发的异常:0xC0000005，执行位置0x00000000时发生访问冲突。

**Comment by drelaptop** [comment]
0x00000000访问冲突，就是空指针异常，什么时候到电脑上看看报错堆栈，可能是 OpenGL 驱动的问题，不是 Bug，论坛有类似的帖子 http://forum.cocos.com/c/cocos2d-x, 请到论坛讨论

**Comment by chenyuxiangg** [comment]
我去看了，然后下载了Github的代码，还是没能解决，依然是这种结果

**Comment by drelaptop** [comment]
这不是代码的问题，是环境配置的问题，GitHub 最新的代码，你可以试着用 cmake 生成 VS 工程，看 cmake 目录下的 Readme.md

**Comment by chenyuxiangg** [comment]
好👌谢啦
