### ISSUE TITLE
自定义事件

### ISSUE THREAD

**Issue by kkli28** [cocos2d/cocos2d-x-docs#141]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/event_dispatcher/custom.md

在写自定义事件的时候，遇到了一个问题。文档中添加listener时使用的是：addEventListenerWithFixedPriority，而新手想要的通常是：addEventListenerWithSceneGraphPriority，因为Node销毁后，如果用前者，可能导致在事件处理函数中调用Node的方法时，出现Node不合法的问题。表述不清楚，见谅。

**Comment by drelaptop** [comment]
对于 `addEventListenerWithSceneGraphPriority `, 如果事件处理函数调用Node方法，Node销毁，可以避免这样的结果吗？如果可以的话，能否解释一下

**Comment by kkli28** [comment]
我是新手，也不太明白，换了addEventListenerWithSceneGraphPriority就不会崩溃了。用addEventListenerWithFixedPriority，该listener在Node销毁后也会存在的吧？如果Node销毁，事件处理函数lambda中调用该Node的函数，this就不可用了，从而导致崩溃。不知道该说法是否正确啊。或者说，能否在文档中该节处再提醒一下两者的关系呢？毕竟新手使用自定义事件时，都是抄文档上的方法的。。。而通常崩溃后也不会注意到是这个地方出错。

**Comment by drelaptop** [comment]
非常感谢反馈，3.17 快发布了，同时要更新文档，到时候重新考虑一下这个地方

**Comment by drelaptop** [comment]
fixed at https://github.com/cocos2d/cocos2d-x-docs/pull/155
