### ISSUE TITLE
suggest to add a new particle design tools [Effekseer] to "Particle System" chapter

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x-docs#146]
English Discuss: http://discuss.cocos2d-x.org/t/effekseer-particle-effect-editor-for-cocos2d-x/39772

中文讨论：http://forum.cocos.com/t/pu/58149

GitHub: https://github.com/effekseer/EffekseerForCocos2d-x

**Comment by slackmoehrle** [comment]
I started a new PR here that includes adding this tool. https://github.com/cocos2d/cocos2d-x-docs/pull/147

**Comment by drelaptop** [comment]
great, I will translate those docs later.
