### ISSUE TITLE
Docs path is different between cocos.com and cocos2d-x.org

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x-docs#149]
For the creator_to_cocos2d-x docs,

```
http://docs.cocos.com/cocos2d-x/manual/en/editors_and_tools/creator_to_cocos2dx.html
http://www.cocos2d-x.org/docs/cocos2d-x/en/editors_and_tools/creator_to_cocos2dx.html
```
One existed `manual`, another not, so that one link links one doc in both website always be failed.

> Creator docs use this type link :
> `[](../../../../cocos2d-x/manual/zh/editors_and_tools/creator_to_cocos2dx.html)`

**Comment by slackmoehrle** [comment]
This has now been fixed recently and we are deploying docs.cocos2d-x.org which finishes this fix.
