### ISSUE TITLE
Software Installations

### ISSUE THREAD

**Issue by amsureshs** [cocos2d/cocos2d-x-docs#159]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/installation/index.md

Typo in the doc. Repeated "be installed" in the following text. 
Cocos2d-x can be installed be installed on OS X, Windows ...

**Comment by slackmoehrle** [comment]
Thanks. Fixed https://github.com/cocos2d/cocos2d-x-docs/pull/148
