### ISSUE TITLE
文档二级菜单报404

### ISSUE THREAD

**Issue by ITBOOSLI** [cocos2d/cocos2d-x-docs#160]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/index.md

**Comment by drelaptop** [comment]
二级菜单的第一节，在英文状态切换至中文时会 404，是由于中英文目录结构的差异导致的，单独访问中文或英文文档不会 404。

原因是大部分英文文档第一节内容较少，翻译到中文只有几句话，按照语言习惯，把英文的两节翻译到中文的一节了，显得内容充实。
