### ISSUE TITLE
add docs for libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x-docs#161]
warning fixed at https://github.com/cocos2d/cocos2d-x/pull/18908

related discuss at https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile/

explain it, and tell our user how to solve this issue

**Comment by slackmoehrle** [comment]
This has been discussed several times on the EN forums with fixes

**Comment by slackmoehrle** [comment]
We could. Why don’t we give it a go. I’ll start it.

**Comment by minggo** [comment]
Adding a FAQ is a good idea.

**Comment by drelaptop** [comment]
that's wonderful, I will follow you changes @slackmoehrle
