### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Ams0x57** [cocos2d/cocos2d-x-docs#162]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/installation/Android-Studio.md

proj.android-studio folder is missing. I used to use it in my android studio last year (maybe with 3.16 version). It no longer exists in 3.17 version. Please enlighten this ASAP. Is android studio no longer supported?

**Comment by slackmoehrle** [comment]
I’ll fix this in the docs. proj.android-Studio is now proj.android. Just open the directory with Android Studio.
