### ISSUE TITLE
能不能有一个js的示例？现在只有C++的

### ISSUE THREAD

**Issue by boiciy** [cocos2d/cocos2d-x-docs#163]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/sprites/polygon.md

能不能有一个js的示例？现在只有C++的

**Comment by drelaptop** [comment]
没有计划，具体请参考 js-tests 测试工程，学习

no plan to add JavaScript Example into our docs, please refer to __js-tests__ project to learn
