### ISSUE TITLE
引擎工具cocos2d-x

### ISSUE THREAD

**Issue by proundwang** [cocos2d/cocos2d-x-docs#166]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/editors_and_tools/cocosCLTool.md
希望官方 大大 ,尽量把文档往详细的方向写。好多官方提供的接口，在官网文档上找不到介绍。新手逛论坛和社区也只能得到一些零碎的信息。

**Comment by drelaptop** [comment]
关于这一部分，你有什么想了解的更详细的东西

https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/editors_and_tools/cocosCLTool.md

**Comment by proundwang** [comment]
比如:创建项目的时使用cocos2d 的预编译库，而不是复制引擎项目的源码，到项目中。

**Comment by drelaptop** [comment]
这个现在已经不支持，没有办法加。使用 cmake 支持预编译库，可以参考引擎目录 cmake/readme
