### ISSUE TITLE
Pre-built Libraries

### ISSUE THREAD

**Issue by mrosalesdiaz** [cocos2d/cocos2d-x-docs#168]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/editors_and_tools/prebuilt_libraries.md

Would be good have more details in how configure the prebuild libs in the different IDEs that cocos2dx supports

**Comment by slackmoehrle** [comment]
We support Android Studio and XCode only for IDE but the prebuilt libs are not being supported much longer.

**Comment by mrosalesdiaz** [comment]
Ok
Thanks
