### ISSUE TITLE
Android 平台

### ISSUE THREAD

**Issue by Crowccc** [cocos2d/cocos2d-x-docs#170]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/installation/Android-Studio.md

cocos3.17创建的工程并没有pro.android_studio，只有pro.android

**Comment by drelaptop** [comment]
多谢反馈，文档需要调整。

旧的 pro.android 是 eclipse 工程，已经移除了，现在 android studio 工程就是 pro.android，导入时请选择这个目录。
