### ISSUE TITLE
add "generateJsonModelDebug FAILED" into Android FAQ

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x-docs#172]
https://github.com/cocos2d/cocos2d-x/issues/18769#issuecomment-420952597

related thread:

https://discuss.cocos2d-x.org/t/solved-android-build-failed-generatejsonmodeldebug/42293
http://forum.cocos.com/t/jenkins/56592

**Comment by slackmoehrle** [comment]
Fixed in PR

**Comment by slackmoehrle** [comment]
I'll add Zh FAQ to docs/ also.
