### ISSUE TITLE
精灵控制

### ISSUE THREAD

**Issue by aaaa1990aaaa** [cocos2d/cocos2d-x-docs#173]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/sprites/manipulation.md

个人感觉  代码例子是不是加上js脚本和lua脚本会好一点 对于像我这样看不懂c++的人 会有更好的用户体验
代码例子可以做成tab标签页的形式 会更好

**Comment by drelaptop** [comment]
多谢反馈，加 lua 脚本接下来考虑做。tab 标签页的方式，是支持的。

> js 无计划

**Comment by aaaa1990aaaa** [comment]
是性能原因吗？

**Comment by drelaptop** [comment]
lua 没加，主要是人力问题，后续会完善。

js 没计划的主要原因，是很多 cocos2d-js 的开发者转 creator 了，creator 有完善的文档。

**Comment by aaaa1990aaaa** [comment]
多谢解答
