### ISSUE TITLE
Basic Actions

### ISSUE THREAD

**Issue by parrieta83** [cocos2d/cocos2d-x-docs#177]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/actions/basic.md

> move_ease_in_back
> [:memo:](https://github.com/cocos2d/cocos2d-x-docs/edit/master/en/actions/basic.md#L166 "Edit") <https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/actions/basic.md#L166>

Hi, 
I was just checking how to use different Easing on actions and noticed "move_ease_in_back" is not defined.
I think it should be defined after the move_ease_in declaration, as:
auto move_ease_in_back = move_ease_in->reverse();
(and move_back should probably be deleted, as it's not used).

Best regards!

**Comment by slackmoehrle** [comment]
Thank you.
