### ISSUE TITLE
Creator to Cocos2d-x 插件

### ISSUE THREAD

**Issue by mrzhao12** [cocos2d/cocos2d-x-docs#188]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/editors_and_tools/creator_to_cocos2dx.md

完成上一步的场景导出后，reader 源码和 Creator 资源都被放到文件系统中了。此时你需要将这些东西，添加到工程中。

增加头文件搜索路径

将这些目录，添加到工程的头文件搜索路径中：

对于 C++ 项目：

```sh
reader
```

这一步提示：
'dragonbones/cocos2dx/CCTextureData.h' file not found

怎么回事？？？？？

求解

**Comment by drelaptop** [comment]
看一下 `CCTextureData .h` 在什么路径，确认一下头文件搜索路径

**Comment by mrzhao12** [comment]
> 看一下 `CCTextureData .h` 在什么路径，确认一下头文件搜索路径

已经好了，再header search path里添加提示缺少的头文件就可以了：
/Users/zhaotong/Desktop/cocos2dx/1120cocosTest/MyGame/Classes/reader

/Users/zhaotong/Desktop/cocos2dx/1120cocosTest/MyGame/Classes/reader/dragonbones/cocos2dx/CCTextureData.h

完美解决问题报错，具体的可以查看教程：

坑在creator_to_cocos2dx 插件（Mac下xcode）
https://www.jianshu.com/p/97421b0cece9
