### ISSUE TITLE
Android 平台

### ISSUE THREAD

**Issue by Crazy-MT** [cocos2d/cocos2d-x-docs#197]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/installation/Android-Studio.md
用 Android Studio 打开 proj.android 项目的时候，需要安装 ninja ， Mac 平台可以执行 brew install ninja 安装。

**Comment by COCO5666** [comment]
老哥，Windows怎么安装ninja？发现使用cmake不行，而且官网文档确实没有这方面的说明

**Comment by slackmoehrle** [comment]
https://github.com/ninja-build/ninja/releases
