### ISSUE TITLE
Error markdown format

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x-docs#37]
https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/physics/concepts.md
**has this content:**

###Material
Materials describe material attributes：

  >-density：It is used to compute the mass properties of the parent body.

  >-friction：It is used to make objects slide along each other realistically.

  >-restitution：It is used to make objects bounce. The restitution value is
 usually set to be between 0 and 1. 0 means no bouncing while 1 means perfect
 bouncing.

**That should be:**

### Material
Materials describe material attributes：

  >- density：It is used to compute the mass properties of the parent body.
  >- friction：It is used to make objects slide along each other realistically.
  >- restitution：It is used to make objects bounce. The restitution value is
 usually set to be between 0 and 1. 0 means no bouncing while 1 means perfect
 bouncing.

**more than one place has the same issue, it should be check when free time**

**Comment by drelaptop** [comment]
Another format error：

https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/physics/collisions.md

category it belongs to. You can also specify what other categories this shape can
collide with. This is done with masking bits. For example:

{% codetabs name="C++", type="cpp" -%}
auto sprite1 = addSpriteAtPosition(Vec2(s_centre.x - 150,s_centre.y));
sprite1->getPhysicsBody()->setCategoryBitmask(0x02);    // 0010
sprite1->getPhysicsBody()->setCollisionBitmask(0x01);   // 0001

sprite1 = addSpriteAtPosition(Vec2(s_centre.x - 150,s_centre.y + 100));
sprite1->getPhysicsBody()->setCategoryBitmask(0x02);    // 0010
sprite1->getPhysicsBody()->setCollisionBitmask(0x01);   // 0001

auto sprite2 = addSpriteAtPosition(Vec2(s_centre.x + 150,s_centre.y),1);
sprite2->getPhysicsBody()->setCategoryBitmask(0x01);    // 0001
sprite2->getPhysicsBody()->setCollisionBitmask(0x02);   // 0010

auto sprite3 = addSpriteAtPosition(Vec2(s_centre.x + 150,s_centre.y + 100),2);
sprite3->getPhysicsBody()->setCategoryBitmask(0x03);    // 0011
sprite3->getPhysicsBody()->setCollisionBitmask(0x03);   // 0011
```
You can check for collisions by checking and comparing _category_ and _collision_
bitmasks like:
```cpp
if ((shapeA->getCategoryBitmask() & shapeB->getCollisionBitmask()) == 0
   || (shapeB->getCategoryBitmask() & shapeA->getCollisionBitmask()) == 0)
{
   // shapes can't collide
   ret = false;
}
{%- endcodetabs %}

**Comment by slackmoehrle** [comment]
These are both fixed. PR started.

**Comment by drelaptop** [comment]
In en/SUMMARY.md
```
-  [Advanced Topics](advanced_topics/index.md)
    - [File System Access](advanced_topics/index.md)
```
`[File System Access]` link error, I will correct it.
