### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by Priority10** [cocos2d/cocos2d-x-docs#62]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/actions/index.md

Since the `next button` link to http://cocos2d-x.org/docs/en/actions/, nothing happens when you click on it.
Expected - go to the next article.
Actual - nothing happens.

**Comment by drelaptop** [comment]
Actually the chapter and the first part of this chapter both link one document file, so that GitBook can't deal with it. 

for I find the [this place of Chinese Doc](http://cocos2d-x.org/docs/zh/actions/) `next button` works well

**Comment by Priority10** [comment]
So can it be fixed? Somehow.

p.s. I saw this problem in other chapters too.

**Comment by slackmoehrle** [comment]
it is this way because them both reference the same URL. Most chapters work correctly because there is more pages for it and they are all named uniquely. I can fix this my renaming some of the pages to a new name. Let me look into how long this would take me.

**Comment by Priority10** [comment]
Nice, but it is kind of like not a critical issue.

**Comment by slackmoehrle** [comment]
I am just going to work the whole day on docs to get many tasks done. Will be helpful to everyone

**Comment by slackmoehrle** [comment]
handled in this PR: https://github.com/cocos2d/cocos2d-x-docs/pull/65

**Comment by Priority10** [comment]
Thank you!
