### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Priority10** [cocos2d/cocos2d-x-docs#63]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/installation/Android-terminal.md

In the left menu, click on Installations, then Android, then frustrating, since the first thing you see is that the document is deprecated. It looks like that Android support is deprecated itself.
Expected - a user should see http://cocos2d-x.org/docs/en/installation/Android-Studio.html page first.

> Android development is a complicated beast.

It does not add enthusiasm as well.

**Comment by drelaptop** [comment]
It's a good suggestion, and we will modify it

**Comment by slackmoehrle** [comment]
handled in this PR: https://github.com/cocos2d/cocos2d-x-docs/pull/65

**Comment by Priority10** [comment]
Thank you!
