### ISSUE TITLE
Installations

### ISSUE THREAD

**Issue by Priority10** [cocos2d/cocos2d-x-docs#64]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/installation/index.md

`Python 2.7.5+` not only `Python 2.7.5`.

In case `win32` project, you need `Visual C++ Redistributable for Visual Studio 2012 x86` and `Visual C++ Redistributable for Visual Studio 2010 x86`.

**Comment by minggo** [comment]
Yep, you are right. But can not use Python 3+.

**Comment by Priority10** [comment]
Then something like `Python 2.7.5+ but not Python 3+`?

**Comment by slackmoehrle** [comment]
I will update docs.

**Comment by slackmoehrle** [comment]
handled in this PR: https://github.com/cocos2d/cocos2d-x-docs/pull/65
