### ISSUE TITLE
Why Cocos2d-x

### ISSUE THREAD

**Issue by onobori** [cocos2d/cocos2d-x-docs#68]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/about/why.md

Viewing the bottom of this page from smartphone, the "Feedback" button is put on the "next" (>) button. That makes to touch the next button difficult.

**Comment by onobori** [comment]
Sorry, I wrote a wrong URL. This issue happens on below.

http://cocos2d-x.org/docs/en/about/getting_started.html

**Comment by slackmoehrle** [comment]
I'll check it out, I am not sure just how much support we will provide from a phone as most developers would view these docs on a computer or some sort. Let me talk it over with the docs team and see. Thank you for reporting this.

**Comment by Priority10** [comment]
Well, some of us learn when we are on the go. :)
I confirm, this happens on many pages, in fact depends on the screen resolution of the device.
The Feedback button should not be floating, this will solve the problem.

**Comment by onobori** [comment]
Think you for responding!

@slackmoehrle Same issue happens on the PC 
browser with a small monitor. Actually, I confirm that a half-width browser has this issue. My laptop's monitor is 12.5 inch.

@Priority10 Great! I'm glad to hear that.

**Comment by slackmoehrle** [comment]
Can you post a few screenshots, please?

**Comment by Priority10** [comment]
iPhone 6
![iphone6](https://user-images.githubusercontent.com/33290238/33418787-929fdfbc-d5b8-11e7-8bd5-db65fd94673f.png)

Nexus 6P
![nexus 6p](https://user-images.githubusercontent.com/33290238/33418794-9834bc18-d5b8-11e7-8812-b93774df8ca5.png)

540x960
![540x960](https://user-images.githubusercontent.com/33290238/33418795-9a6ebf42-d5b8-11e7-9db4-1a47653ded15.png)

**Comment by onobori** [comment]
Sorry for a late reply.

Xperia Z5
![screenshot_20171128-183018](https://user-images.githubusercontent.com/1475680/33516924-129e2afa-d7be-11e7-8f36-20c34ede3d2f.png)

683x768
![pc_firefox](https://user-images.githubusercontent.com/1475680/33516926-141b8e5e-d7be-11e7-87b1-3ca80c464ada.png)

**Comment by drelaptop** [comment]
maybe we can realize "Feedback" by footer, I find some [footer plugins](https://plugins.gitbook.com/browse?q=footer), that will make some help.

**Comment by slackmoehrle** [comment]
Cool, thanks for looking. Lets have a try with these locally. I can help.

**Comment by drelaptop** [comment]
make feedback button responsive, the logic is:
```
  if (document.body.offsetHeight * 9 >= document.body.offsetWidth * 12) {
     not show feedback button;
  }else{
     show feedback button;
  }
```
docs on cocos2d-x.org have fixed this @onobori

**Comment by Priority10** [comment]
Nice. Thanks @drelaptop  !
