### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Priority10** [cocos2d/cocos2d-x-docs#69]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/installation/Linux.md

Link Cocos Command-line tool does not work.
404 error.

@slackmoehrle You need another new rule. :D

**Comment by slackmoehrle** [comment]
I dont need a new rule, I just need to correct the URL. I will verify the rest of the installation docs are correct too.

**Comment by Priority10** [comment]
My bad.
Then we will stop on how many rules? 105 now?))

**Comment by Priority10** [comment]
It seems that this issue is fixed now. Thanks @slackmoehrle  !
