### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Priority10** [cocos2d/cocos2d-x-docs#70]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/installation/Linux.md

https://github.com/cocos2d/cocos2d-x/issues/18488
I'm not sure where the user got this. `Linux` seems like the most relevant page.

@slackmoehrle Can you confirm this? How about close or transfer that issue?

**Comment by slackmoehrle** [comment]
I will check this out. Thank you.

**Comment by Priority10** [comment]
Any progress?

**Comment by slackmoehrle** [comment]
I have revamped the instructions testing on 17.x and now I will backtest on 16.04. I think there will be a few minor corrections. https://github.com/cocos2d/cocos2d-x-docs/pull/136#issuecomment-373837989

I no longer use install-linux-deps.sh
