### ISSUE TITLE
命令行 (已弃用)

### ISSUE THREAD

**Issue by djwind** [cocos2d/cocos2d-x-docs#89]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/installation/Android-terminal.md

![image](https://user-images.githubusercontent.com/3746553/34036286-ac6554aa-e1bf-11e7-8d23-09d8b42e7afe.png)

This command "brew install android-sdk android-ndk" is no available.

**Comment by drelaptop** [comment]
`brew` is package manager tools in macOS, you need to install by yourself. see: https://brew.sh/

**Comment by slackmoehrle** [comment]
We just need to fix the instructions now. It has moved:
```sh
Error: No available formula with the name "android-sdk"
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
```
I'll update the English docs.

**Comment by drelaptop** [comment]
ok, I will update Chinese docs too

**Comment by slackmoehrle** [comment]
The fix is:
```sh
$ brew tap caskroom/cask
$ brew cask install android-sdk android-ndk
```

**Comment by drelaptop** [comment]
the same see #91 @djwind, close issue

**Comment by djwind** [comment]
My "brew" is installed, just to tell you that you can update the document.

**Comment by drelaptop** [comment]
yes, I will. this have been update in Github [this](https://github.com/cocos2d/cocos2d-x-docs/blob/master/zh/installation/Android-terminal.md), and a little later in `www.cocos.com` @djwind
