### ISSUE TITLE
更新中文文档 - 环境搭建

### ISSUE THREAD

**Issue by drelaptop** [cocos2d/cocos2d-x-docs#9]
## 环境搭建

- [x] Android - Android Studio
- [x] Win32 - Visual Studio 
- [x] Android - Visual Studio `Don't Support`
- [x] macOS 平台 
- [x] iOS 平台
- [x] Linux 平台
- [x] Android - Eclipse `` `Deprecated`

- [x] Android - Command-line

**Comment by slackmoehrle** [comment]
@minggo @drelaptop Linux is now done. Tested with Ubuntu 16.04.1. The only issue I ran into is the __fmod__ dependency, which is already a known issue for Linux developers.

**Comment by minggo** [comment]
Yep, i have not idea with the issue, can we mention about how to fix it manually in the doc?

**Comment by drelaptop** [comment]
`Android - Command-line`, this part I also didn't test, will you test it in the next weeks. now I have begun translation @slackmoehrle

**Comment by slackmoehrle** [comment]
@minggo sure, we have some GitHub issues that state how to fix it. I will review those and add the steps into the doc for Linux.

@drelaptop Android Command-line on what platforms?
