### ISSUE TITLE
Why Cocos2d-x

### ISSUE THREAD

**Issue by mfarooqi** [cocos2d/cocos2d-x-docs#92]
URL : https://github.com/cocos2d/cocos2d-x-docs/blob/master/en/about/why.md

On mobile display. Next button (to navigate next page) is under feedback button. 

Pressed next button Luckily but difficulty 

Thank you

**Comment by drelaptop** [comment]
thanks, and this issue is discussing in #68

**Comment by onobori** [comment]
Thanks a lot!
